name: Build and Deploy to Codeberg Pages

on:
  push:
    branches:
      - pages

jobs:
  build_and_deploy:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 20
      - name: Install and Build
        run: npm ci && npm run build

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.repository_owner }}.codeberg.page/
          token: ${{ forge.token }}
          source: dist/
